### ISSUE TITLE
This does not appear to work when the Pico is connected via UART direct connection. 

### ISSUE THREAD

**Issue by ThunderClap86** [Drachenkaetzchen/VoronMisc#3]
Any help if we are using the UART connection and not the USB? I cannot seem to make this work, apparently I am inept.

**Comment by Drachenkaetzchen** [comment]
Sorry, can't provide you with help there. If this is about a Voron, please ask in the voron forum or discord.

**Comment by ThunderClap86** [comment]
Okay, how would I delete what this has added to my build please? Since installing it, it is preventing my klipper.service from starting and is preventing restarts because it fails the automated reset.

**Comment by Drachenkaetzchen** [comment]
You need to remove the lines added to the klipper service unit file. I'm afraid I can't give you verbose instructions.
